### ISSUE TITLE
It is illegal to put an inverse side one-to-many or many-to-many association on mapped superclass

### ISSUE THREAD

**Issue by Yaghiyah** [sonata-project/SonataPageBundle#610] opened 2016-02-07 16:27 UTC
Can someone please help me, I just started out with SonataPageBundle

I'm getting an error   when running the command *\* doctrine:schema:update --force**

> It is illegal to put an inverse side one-to-many or many-to-many association on mapped superclass 'Sonata\PageBundle\Entity\BasePage#children'.  

Here is my dependencies list. 

```
{
    "name": "symfony-cmf/standard-edition",
    "homepage": "http://cmf.symfony.com",
    "license": "MIT",
    "type": "project",
    "description": "The \"Symfony CMF Standard Edition\" distribution",
    "authors": [
        {
            "name": "Symfony CMF Community",
            "homepage": "https://github.com/symfony-cmf/standard-edition/contributors"
        }
    ],
    "autoload": {
        "psr-0": { "": "src/" }
    },
    "minimum-stability": "stable",
    "require": {
        "php": ">=5.3.3",
        "symfony/symfony": "~2.5",
        "doctrine/doctrine-bundle": "~1.2",
        "doctrine/data-fixtures": "~1.0",
        "doctrine/doctrine-cache-bundle": "~1.0",
        "twig/extensions": "~1.0",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "symfony-cmf/symfony-cmf": "1.2.*",
        "symfony-cmf/simple-cms-bundle": "1.2.*",
        "symfony-cmf/create-bundle": "1.2.*",
        "jackalope/jackalope-doctrine-dbal": "1.1.*",
        "sensio/distribution-bundle": "~3.0",
        "sensio/framework-extra-bundle": "^3.0",
        "incenteev/composer-parameter-handler": "~2.0",
        "nelmio/alice": "~1.0",
        "sonata-project/admin-bundle": "~2.3",
        "sonata-project/doctrine-phpcr-admin-bundle": "^1.2",
        "sonata-project/block-bundle": "~2.2",
        "sonata-project/doctrine-orm-admin-bundle": "^2.3",
        "friendsofsymfony/user-bundle": "~1.3",
        "friendsofsymfony/jsrouting-bundle": "^1.5",
        "symfony-cmf/media-bundle": "^1.2",
        "liip/imagine-bundle": "^1.3",
        "helios-ag/fm-elfinder-bundle": "^5.1",
        "sonata-project/media-bundle": "^2.3",
        "phpunit/phpunit": "^4.8",
        "sonata-project/page-bundle": "^2.3",
        "sonata-project/easy-extends-bundle": "^2.1",
        "sonata-project/datagrid-bundle": "2.2.*@dev",
        "sonata-project/user-bundle": "^2.2"
    },
    "require-dev": {
        "liip/functional-test-bundle": "~1.0",
        "sensio/generator-bundle": "~2.3"
    },
    "scripts": {
        "post-install-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Symfony\\Cmf\\Bundle\\CreateBundle\\Composer\\ScriptHandler::downloadCreate",
            "Symfony\\Cmf\\Bundle\\CreateBundle\\Composer\\ScriptHandler::downloadCreateAndCkeditor",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile"
        ],
        "post-update-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Symfony\\Cmf\\Bundle\\CreateBundle\\Composer\\ScriptHandler::downloadCreate",
            "Symfony\\Cmf\\Bundle\\CreateBundle\\Composer\\ScriptHandler::downloadCreateAndCkeditor",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile"
        ]
    },
    "config": {
        "bin-dir": "bin",
        "component-dir": "web/assets"
    },
    "extra": {
        "symfony-app-dir": "app",
        "symfony-web-dir": "web",
        "incenteev-parameters": {
            "file": "app/config/parameters.yml"
        },
        "branch-alias": {
            "dev-master": "1.3-dev"
        }
    }
}

```

**Comment by Yaghiyah** [comment] 2016-02-15 11:35
Still nothing ive rolled back to  "symfony/symfony": "~2.2", I hope someone can explain why I`m getting this issue.

**Comment by jordisala1991** [comment] 2018-03-08 00:09
This issue is very old and probably fixed on latest releases. Closing.

Can you check against the latest release and ping me back if the issue is still there?

**Closed by jordisala1991** 2018-03-08 00:09 UTC
