### ISSUE TITLE
On block delete in page composer redirect to that page composer not to BlockAdmin list

### ISSUE THREAD

**Issue by haivala** [sonata-project/SonataPageBundle#1601] opened 2022-09-08 08:56 UTC
Now it redirects to BlockAdmin list that is not usable and not shown anywhere else.

Edit: This is problem with 3.x and 4.x.

1. you go to `/admin/app/sonatapagepage/1/compose`
2. select block to delete in the composer
3. delete it
4. you are redirected to `/admin/app/sonatapageblock/list?composer=1&filter[_page]=1&filter[_per_page]=25&filter[page][value]=1` not back to `/admin/app/sonatapagepage/1/compose`

**Comment by VincentLanglet** [comment] 2022-09-08 09:10
> Now

The current stable branch is 3.x. I assume you're talking about 4.x but it's not even clear in you one-line-issue.
The more it's described, it's even better with screenshot and url, the more it will be solved.

Also for 4.x "bugs", I recommend to report them in https://github.com/sonata-project/SonataPageBundle/issues/1495 and @eerison will add it into his list https://github.com/sonata-project/SonataPageBundle/issues/1495#issue-1318060076

**Comment by eerison** [comment] 2022-09-08 09:16
Exactly, for small issues I'm grouping them into #1495

But as @VincentLanglet says, try to describe better the issues, specially with screenshot or even better a small video with the reproduction (it's quickly and help a lot to undestand how you reproduce the issue)

**Comment by haivala** [comment] 2022-09-08 09:18
This is problem with 3.x and 4.x.

1. you go to `/admin/app/sonatapagepage/1/compose`
2. select block to delete in the composer
3. delete it
4. you are redirected to `/admin/app/sonatapageblock/list?composer=1&filter[_page]=1&filter[_per_page]=25&filter[page][value]=1` not back to `/admin/app/sonatapagepage/1/compose`

**Comment by haivala** [comment] 2022-09-08 09:20
As this is problem with both 3.x and 4.x I thought it would be better to have new issue about it and not require it in 4.x release.

**Comment by VincentLanglet** [comment] 2022-09-08 09:21
> As this is problem with both 3.x and 4.x I thought it would be better to have new issue about it and not require it in 4.x release.

I agree.
But I don't know a lot this bundle, it was hard to me to understand this.

> This is problem with 3.x and 4.x.
> 
> 1. you go to `/admin/app/sonatapagepage/1/compose`
> 2. select block to delete in the composer
> 3. delete it
> 4. you are redirected to `/admin/app/sonatapageblock/list?composer=1&filter[_page]=1&filter[_per_page]=25&filter[page][value]=1` not back to `/admin/app/sonatapagepage/1/compose`

This is better ; I added to the first message.

**Comment by eerison** [comment] 2022-09-08 09:23
Well as I can see the problem is just the redirect, I agree that it need be fixed in 3.x but as it's not a critical issue, I would say that it has less priority then 4.x release.

**Comment by VincentLanglet** [comment] 2022-09-08 09:25
> Well as I can see the problem is just the redirect, I agree that it need be fixed in 3.x but as it's not a critical issue, I would say that it has less priority then 4.x release.

Yeah. We try to fix the bug in 4.x that we introduced (and which were working in 3.x) first.
So a specific issue for this issue is meaningful ; it wasn't clear to me before in which situation we were.

**Comment by eerison** [comment] 2022-09-28 11:23
Hey @haivala could you test it again please.

I tested using the last version of 4.x and it's working as expected!

**Comment by haivala** [comment] 2022-09-28 11:37
It does not work. I'm using 4.x-dev.

I have block with id 18 and I want to delete it. I open the composer and edit the block. There is buttons Update or Delete. Delete button redirects me to `/admin/app/sonatapageblock/18/delete?composer=1` and asks `Are you sure you want to delete the selected...`. When I click yes it redirect me to BlockAdmin list at `admin/app/sonatapageblock/list?composer=1&filter[_page]=1&filter[_per_page]=25`
I'm guessing you used the ajax version of block delete? button says remove and can be found at composer when you hover on a block. That does work as expected.

**Comment by haivala** [comment] 2022-09-28 11:44
What we could do is just remove the delete button in composer as the same thing can be done with the ajax remove.

**Comment by eerison** [comment] 2022-09-28 11:59
Then it's not in composer page, because after delete it's redirecting to anywhere. it made a ajax request

are you sure that is it in composer page?

**Comment by haivala** [comment] 2022-09-28 12:39
I just explained that you need to open the block edit dialogue in composer page

**Comment by haivala** [comment] 2022-09-28 12:41
![2022-09-28_154050-area](https://user-images.githubusercontent.com/3918267/192780943-74b9662e-bc38-4a44-8c63-341e69efce88.png)

**Comment by eerison** [comment] 2022-09-28 12:56
sorry I didn't follow you!

**Comment by eerison** [comment] 2022-09-28 13:02
https://user-images.githubusercontent.com/6358755/192785187-7990e41b-ce18-4b1d-bde1-d24196495417.mov

as I said , remove block from composer page works ☝🏼

**Comment by haivala** [comment] 2022-09-28 13:55
Again, open the block edit and then push `delete` button which is next to the `update` button
Don't use the `remove` button. That works

**Comment by eerison** [comment] 2022-09-28 14:28
1- Your ticket description is wrong then, you are saying that this issue is in `composer page`.
2- It's working in block list also 👇🏼 

https://user-images.githubusercontent.com/6358755/192805724-9018efca-26a5-4121-98a0-d76bc66b2442.mov

if it's not the page, please provider a better description with screenshots and what exactly urls it's happening, if it's possible record your screen with this issue.

**Comment by haivala** [comment] 2022-09-28 14:30
![2022-09-28_172941-area](https://user-images.githubusercontent.com/3918267/192806214-69f1b7c4-d67a-409d-be36-f612568eddde.png)

**Comment by haivala** [comment] 2022-09-28 14:30
can you see the delete button now?

**Comment by eerison** [comment] 2022-09-28 14:32
Ok know it's clear where is the issue!

**Closed as completed** 2022-10-02 16:17 UTC
Labels: feature
