### ISSUE TITLE
multisite redirects are missing site.relativePath

### ISSUE THREAD

**Issue by thms** [sonata-project/SonataPageBundle#620] opened 2016-03-03 09:58 UTC
Configure two sites, relative path /one and /two
Configure nginx to handle both and use fcgi to proxy to php.
Configure app_dev.php to use $request = RequestFactory::createFromGlobals('host_with_path');

Force a redirect, either via impersonating a user, or by redirecting in a authentication success listener. Either f these will create a RedirectResponse that uses SiteRequest#getUri(). 
The problem is that getUri() builds the URI without the site's relative path, so the redirects are invalid.
I have tried a few ways to fix this, but always run into issues with inheritance (so I can't inherit and access private members), or hardcoded includes.

Config (as it is relevant to the discussion):

``` yaml
sonata_page:
    class:
#        page: AppBundle\Entity\Page
#        site: AppBundle\Entity\Site
#        block: AppBundle\Entity\Block
#        snapshot: AppBundle\Entity\Snapshot
    direct_publication: %kernel.debug%
    multisite: host_with_path
    use_streamed_response: true # set the value to false in debug mode or if the reverse proxy does not handle streamed response
    # Decide which routes to exclude from handling via the th CMS
    ignore_route_patterns:
        - ^(.*)admin(.*)   # ignore admin route, ie route containing 'admin'
        - ^_(.*)          # ignore symfony debugger routes

    ignore_routes:
        - sonata_page_cache_esi
        - sonata_page_cache_ssi
        - sonata_page_js_sync_cache
        - sonata_page_js_async_cache
        - sonata_cache_esi
        - sonata_cache_ssi
        - sonata_cache_js_async
        - sonata_cache_js_sync
        - sonata_cache_apc

    ignore_uri_patterns:
        - ^/admin\/   # ignore admin route, ie route containing 'admin'

    page_defaults:
        homepage: {decorate: false, enabled: false} # disable decoration for homepage, key - is a page route
```

**Comment by K3yro** [comment] 2016-10-20 08:35
I've had similar issues:
- https was ignored
- app_dev was ignored

I've done following steps to solve this problem:
1. Create your own HostPathSiteSelector that extends HostPathSiteSelector provided by sonata team
2. Override handleKernelRequest method and replace following lines (68-70 in original file)
```php
if (!$this->site && $defaultSite) {
     $event->setResponse(new RedirectResponse($defaultSite->getUrl(), 301));
 }
```
with your own solution i.e.
```
 if (!$this->site && $defaultSite) {
            $base = $request->getBaseUrl();
            $controller = strpos($base,'app_dev.php') !== false ? '/app_dev.php':'';
            $targetUrl = sprintf("%s://%s%s%s",$request->getScheme(),$defaultSite->getHost(),$controller,$defaultSite->getRelativePath());
            $event->setResponse(new RedirectResponse($targetUrl, 301));
        }
```
3. You need to replace HostPathSiteSelector class with your own in service, to do that you need to add to parameters.yml 
```yml
 sonata.page.site.selector.host_with_path.class: 'Application\Sonata\PageBundle\Site\HostPathSiteSelector'
```

My solution is not perfect but it works (so far) ;)

So the problem is in Sonata\PageBundle\Model\Site->getUrl() code below
```php
    public function getUrl()
    {
        if ($this->isLocalhost()) {
            return $this->getRelativePath();
        }

        return sprintf('http://%s%s', $this->getHost(), $this->getRelativePath());
    }
```
in return statement we force http and ignore dev/test controller.

Sorry for my english, i'm still learning

**Comment by jordisala1991** [comment] 2018-03-20 22:00
Problem with protocol fixed here: https://github.com/sonata-project/SonataPageBundle/pull/765

For the problem with app_dev, I did an explanation on why we shouldnt handle it on Sonata’s end here: #444 

Closing, if you think this is an issue on our end please ping me and we will discuss it.

**Closed by jordisala1991** 2018-03-20 22:00 UTC
