### ISSUE TITLE
sonata_block_render with 'sonata.page.block.children_pages' will fail if you pass a page id

### ISSUE THREAD

**Issue by blaues0cke** [sonata-project/SonataPageBundle#455] opened 2015-01-29 17:10 UTC
If you run this code (for example) in a twig template:

```
{{ sonata_block_render({ 'type': 'sonata.page.block.children_pages' },
    {
        'current': false,
        'pageId': '1',
        'page_id': '1',
    })
}}
```

The code will crash because its tries to get "children" on "1" (string). When you dig a little bit in the code, you can see that `$block->getSetting('pageId', null)` in `ChildrenPagesBlockService->load` is `null`.

When you use the same block with the composer in sonata admin, the code in `ChildrenPagesBlockService->load` works. But it still crashes afterwards.

Tried to fix this, but it seems that I am not deep enough in sonata pages... :-)

**Comment by blaues0cke** [comment] 2015-01-30 07:29
This may occur because `sonata_block_render` runs in a second $request that does not now its $site

**Comment by moonraking** [comment] 2015-07-03 08:20
I think part of the problem is line 56 of vendor/sonata-project/page-bundle/CmsManager/CmsPageManager.php

```php
$page = $pageId;
```
should be:
```php
$page = $this->getPageById($page);
```

Quick check https://github.com/sonata-project/SonataPageBundle/blob/master/CmsManager/CmsPageManager.php , this is fixed now?

**Comment by jordisala1991** [comment] 2018-03-10 10:42
This is probably fixed already. https://github.com/sonata-project/SonataPageBundle/blob/3.x/src/CmsManager/CmsPageManager.php#L61

Things that comes to my mind: not passing the correct key, or using a string for the value when it is an int.

Closing. If you still have this issue after my comment, please ping me to reopen with more info.

**Closed by jordisala1991** 2018-03-10 10:42 UTC
